### PR TITLE
Need to add URL with scheme

### PR DESCRIPTION
**Pull request by yabuki**
Hello deno document maintainer.

I evaluated this sample with deno repl. This sample should add URL `jsr' scheme.

### CODE REVIEW

**Comment by yabuki** [comment]
If you assume `deno add @std/assert` and `deno add @std/async`, please write it down in documentation.

**Review by marvinhagemeister — APPROVED** [review]
Thanks!

**Comment by marvinhagemeister** [comment]
Looks like there are merge conflicts in the PR. Can you rebase it against `main`?

**Comment by yabuki** [comment]
I cleaned up commit. Please check it out.

**Pull request merged**
