### PR TITLE
adding JWT parsing example

### PR DESCRIPTION
**Pull request by aaronhmiller**
an example for your consideration

### CODE REVIEW

**Comment by aaronhmiller** [comment]
Advice on how to address the failing build check welcome.

**Comment by thisisjofrank** [comment]
Please run `deno fmt`, should fix the failing build

**Comment by aaronhmiller** [comment]
thank you for the advice @thisisjofrank ran `deno fmt` but it didn't change anything. the error looks related to parsing the dependency, and I don't yet know how to resolve that issue:

Download https://jsr.io/@std/path/1.0.0-rc.1/_common/strip_trailing_separators.ts
⚠️ Orama documents were not generated.
error: Uncaught (in promise) Error: Invalid resource: {https://deno.land/x/djwt@v3.0.2/mod.ts}
      throw new Error(`Invalid resource: ${resource}`);
            ^
    at parseExample (file:///home/runner/work/docs/docs/examples.page.tsx:565:13)
    at file:///home/runner/work/docs/docs/examples.page.tsx:49:15
    at Array.map (<anonymous>)
    at default (file:///home/runner/work/docs/docs/examples.page.tsx:42:26)
    at default.next (<anonymous>)
    at Async-from-Sync Iterator.next (<anonymous>)
    at Renderer.renderPages (https://cdn.jsdelivr.net/gh/lumeland/lume@864fb83b508b4164afa8cedef100db672b883152/core/renderer.ts:104:26)
    at async Site.#buildPages (https://cdn.jsdelivr.net/gh/lumeland/lume@864fb83b508b4164afa8cedef100db672b883152/core/site.ts:640:5)
    at async Site.build (https://cdn.jsdelivr.net/gh/lumeland/lume@864fb83b508b4164afa8cedef100db672b883152/core/site.ts:540:9)
    at async buildSite (https://cdn.jsdelivr.net/gh/lumeland/lume@864fb83b508b4164afa8cedef100db672b883152/cli/utils.ts:45:3)
Error: Process completed with exit code 1.

**Comment by aaronhmiller** [comment]
I'm going to remove this PR for now as the failing deploy job's errors are not making sense and a fix doesn't seem to be forthcoming.

**Pull request closed without merging**
