### PR TITLE
Improve examples layout

### PR DESCRIPTION
**Pull request by donjo**
Note: copy button is broken on examples, unrelated to this PR, but will fix in a different PR. 

This PR aims to build a flex-based layout for the content on the examples pages to help standardize the spacing between content blocks.

It also removes some metadata at the top of the page that we deemed to be not helpful to users at this time. 

Screenshot 2024-09-10 at 2 33 57 PM

Screenshot 2024-09-05 at 10 58 13 AM

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]

**Review by thisisjofrank — CHANGES_REQUESTED** [review]
The gaps between the code samples should not be there, the code samples should look as if they are all one document

**Comment by lucacasonato** [comment]
Also the copy button is broken here

**Comment by donjo** [comment]
@thisisjofrank updated! ptal. 

(copy button still untouched but we can fix in another pr)

**Review by thisisjofrank — APPROVED** [review]
Yay!

**Pull request merged**
